### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by eosclassicteam** [eosclassic/go-eosclassic#1]
- [x] Change go import path
- [x] Change default RPC & listening port
- [x] Implement block halving point on block 170,000

**Comment by eosclassicteam** [comment]
Voting result for block reward halving https://twitter.com/eosclassicio/status/1012986381600055297

**Comment by eosclassicteam** [comment]
- [ ] Reduce reward to 42 (total 60)

Voting result https://twitter.com/eosclassicio/status/1012988550994751489

**Comment by eosclassicteam** [comment]
ahmednazarchishti - Last Thursday
just wanted let (especially the dev team ) you guys know that i cant launch ethereum and eosclassic  windows wallet simultaneously. one or the other gets confused and shows either ether balance or eosc balance. depending which wallet you launched first.

**Comment by eosclassicteam** [comment]
Now implemented
